// Isolated Linux integration: real sshd, rsync, Astro export and nginx. No cloud credentials.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createPublisher } from "../publisher.mjs";
import { copyTree, pendingChanges, readJson } from "../publish-store.mjs";
import { saveArticle } from "../article-store.mjs";
import { run } from "../ssh-deploy.mjs";

if (!process.env.MYSITE_SSH_TEST && process.platform !== "linux") throw new Error("Run this test in the isolated Docker image");
const root = fs.mkdtempSync(path.join(os.tmpdir(), "mysite-ssh-"));
fs.chmodSync(root, 0o755);
const children = [];
try {
  for (const name of ["src", "scripts", "public", "package.json", "package-lock.json", "astro.config.mjs", "tsconfig.json"]) copyTree(path.join("/app", name), path.join(root, name));
  fs.symlinkSync("/app/node_modules", path.join(root, "node_modules"), "dir");
  const publisher = createPublisher(root);
  const remotePath = path.join(root, "remote-site");
  publisher.configure({ host: "127.0.0.1", user: "root", port: 2222, remotePath, siteUrl: "http://127.0.0.1:8090" });
  const key = path.join(root, "test-key");
  const hostKey = path.join(root, "host-key");
  await run("ssh-keygen", ["-t", "ed25519", "-N", "", "-f", key]);
  await run("ssh-keygen", ["-t", "ed25519", "-N", "", "-f", hostKey]);
  publisher.credential("key", fs.readFileSync(key, "utf8"));
  publisher.credential("hosts", `[127.0.0.1]:2222 ${fs.readFileSync(`${hostKey}.pub`, "utf8")}`);
  fs.mkdirSync("/run/sshd", { recursive: true });
  fs.writeFileSync(path.join(root, "banner"), "Authorized deployment test only.\n");
  const sshConfig = path.join(root, "sshd_config");
  fs.writeFileSync(sshConfig, `Port 2222\nListenAddress 127.0.0.1\nHostKey ${hostKey}\nAuthorizedKeysFile ${key}.pub\nPermitRootLogin prohibit-password\nPasswordAuthentication no\nUsePAM no\nStrictModes no\nPidFile ${root}/sshd.pid\nBanner ${root}/banner\n`);
  children.push(spawn("/usr/sbin/sshd", ["-D", "-e", "-f", sshConfig], { stdio: "ignore" }));
  const nginxConfig = path.join(root, "nginx.conf");
  fs.writeFileSync(nginxConfig, `pid ${root}/nginx.pid; error_log stderr; events {} http { include /etc/nginx/mime.types; access_log off; server { listen 127.0.0.1:8090; root ${remotePath}/current; location / { try_files $uri $uri/ =404; } } }`);
  children.push(spawn("nginx", ["-c", nginxConfig, "-g", "daemon off;"], { stdio: "ignore" }));
  await new Promise((resolve) => setTimeout(resolve, 400));
  await publisher.check();
  console.log("PASS real SSH connection and pinned host fingerprint");
  const image = fs.readFileSync(path.join(root, "public/articles/cat-moon.jpg"));
  const save = (slug, body) => publisher.mutate(() => saveArticle(root, { title: slug, slug, previousSlug: fs.existsSync(path.join(root, `src/content/articles/${slug}.md`)) ? slug : "", category: "生活", summary: body, body, cover: { blob: "image" } }, new Map([["image", { buffer: image, ext: ".jpg" }]])));
  save("ssh-ready", "VISIBLE_FIRST_VERSION");
  save("ssh-secret", "PRIVATE_NEVER_UPLOAD");
  const first = await (await publisher.start({ mode: "deploy", selection: pendingChanges(root).filter((c) => c.key.endsWith("ssh-ready.md")) })).completion;
  assert.equal(first.status, "published", first.error);
  assert.match(await fetch("http://127.0.0.1:8090/articles/ssh-ready/").then((r) => r.text()), /VISIBLE_FIRST_VERSION/);
  assert.equal((await fetch("http://127.0.0.1:8090/articles/ssh-secret/")).status, 404);
  assert.equal((await fetch("http://127.0.0.1:8090/articles/ssh-secret.jpg")).status, 404);
  assert.equal((await fetch("http://127.0.0.1:8090/api/publishing")).status, 404);
  console.log("PASS full Astro export, real rsync upload, nginx article, draft route and image isolation");
  save("ssh-ready", "VISIBLE_SECOND_VERSION");
  const second = await (await publisher.start({ mode: "deploy", selection: pendingChanges(root).filter((c) => c.key.endsWith("ssh-ready.md")) })).completion;
  assert.equal(second.status, "published", second.error);
  assert.match(await fetch("http://127.0.0.1:8090/articles/ssh-ready/").then((r) => r.text()), /VISIBLE_SECOND_VERSION/);
  await publisher.revert(first.id);
  assert.match(await fetch("http://127.0.0.1:8090/articles/ssh-ready/").then((r) => r.text()), /VISIBLE_FIRST_VERSION/);
  assert.equal(createPublisher(root).status().state.current, first.id);
  console.log("PASS second publish, atomic switch, real SSH rollback, persisted baseline after restart");
  fs.writeFileSync(path.join(remotePath, "releases", second.id, "index.html"), "CORRUPTED");
  await assert.rejects(() => publisher.revert(second.id), /执行失败/);
  assert.match(await fetch("http://127.0.0.1:8090/articles/ssh-ready/").then((r) => r.text()), /VISIBLE_FIRST_VERSION/);
  console.log("PASS corrupted remote release rejected without replacing current site");
  const state = readJson(path.join(root, ".studio/state.json"));
  fs.unlinkSync(path.join(root, ".studio/state.json"));
  await publisher.recover();
  assert.equal(publisher.status().state.current, state.current);
  console.log("PASS reconciliation of remote current version with local records");
} finally {
  for (const child of children) child.kill("SIGTERM");
  fs.rmSync(root, { recursive: true, force: true });
}
